name: Run CardValidation Tests in Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t cardvalidation-tests -f Dockerfile.Tests .

    - name: Extract test results
      run: |
        docker create --name cardvalidation-container cardvalidation-tests
        docker cp cardvalidation-container:/app/TestResults ./TestResults
        docker rm cardvalidation-container

    - name: Upload Unit Test Results
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: TestResults/unit-tests.trx

    - name: Upload Integration Test Results
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-results
        path: TestResults/integration-tests.trx

    - name: Generate HTML Reports
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:TestResults/*.trx -targetdir:TestResults/Report -reporttypes:Html

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: TestResults/Report