name: Run CardValidation Tests in Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Build Docker image
    - name: Build Docker image
      run: docker build -t cardvalidation-tests -f Dockerfile.Tests .

    # Step 3: Extract test results from container
    - name: Extract test results
      run: |
        docker create --name cardvalidation-container cardvalidation-tests
        docker cp cardvalidation-container:/app/TestResults ./TestResults
        docker rm cardvalidation-container

    # Step 4: Upload Unit Test Results
    - name: Upload Unit Test Results
      uses: actions/upload-artifact@v4
      with:
        name: cardvalidation-unit-test-results
        path: TestResults/unit-tests.trx

    # Step 5: Upload Integration Test Results
    - name: Upload Integration Test Results
      uses: actions/upload-artifact@v4
      with:
        name: cardvalidation-integration-test-results
        path: TestResults/integration-tests.trx

    # Step 6: Generate HTML Reports
    - name: Generate HTML Reports
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:TestResults/*.trx -targetdir:TestResults/Report -reporttypes:Html

    # Step 7: Upload HTML Report
    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: TestResults/Report