// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CardValidation.Tests.Integration.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ValidateCreditCardFeature : object, Xunit.IClassFixture<ValidateCreditCardFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CardValidation.feature"
#line hidden
        
        public ValidateCreditCardFeature(ValidateCreditCardFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "Validate Credit Card", "  As a QA engineer\r\n  I want to validate credit card numbers via the API\r\n  So th" +
                    "at I can ensure the correct payment system is returned", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Full card details is valid")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "Full card details is valid")]
        public async System.Threading.Tasks.Task FullCardDetailsIsValid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Full card details is valid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("I have the owner \"Jane Doe\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.GivenAsync("I have a credit card number \"4111111111111111\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
    await testRunner.GivenAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
    await testRunner.GivenAsync("I have the date \"09/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Visa card number is valid")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "Visa card number is valid")]
        public async System.Threading.Tasks.Task VisaCardNumberIsValid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Visa card number is valid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("I have the owner \"Jane Doe\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 16
    await testRunner.GivenAsync("I have a credit card number \"4111111111111111\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
    await testRunner.GivenAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
    await testRunner.GivenAsync("I have the date \"09/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
    await testRunner.AndAsync("the response should contain \"Visa\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="MasterCard card number is valid")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "MasterCard card number is valid")]
        public async System.Threading.Tasks.Task MasterCardCardNumberIsValid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("MasterCard card number is valid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.GivenAsync("I have the owner \"Jane Doe\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
    await testRunner.GivenAsync("I have a credit card number \"5500000000000004\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
    await testRunner.GivenAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
    await testRunner.GivenAsync("I have the date \"09/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 28
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 30
    await testRunner.AndAsync("the response should contain \"MasterCard\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AmericanExpress card number is valid")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "AmericanExpress card number is valid")]
        public async System.Threading.Tasks.Task AmericanExpressCardNumberIsValid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("AmericanExpress card number is valid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 33
    await testRunner.GivenAsync("I have the owner \"Jane Doe\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
    await testRunner.GivenAsync("I have a credit card number \"340000000000009\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
    await testRunner.GivenAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
    await testRunner.GivenAsync("I have the date \"09/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 37
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 39
    await testRunner.AndAsync("the response should contain \"AmericanExpress\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Owner should be required")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "Owner should be required")]
        public async System.Threading.Tasks.Task OwnerShouldBeRequired()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Owner should be required", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 42
    await testRunner.GivenAsync("I have a credit card number \"340000000000009\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 43
    await testRunner.GivenAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 44
    await testRunner.GivenAsync("I have the date \"09/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 45
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
    await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 47
    await testRunner.AndAsync("the response should contain validation error \"Owner is required\" for field \"Owner" +
                        "\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Owner name with numbers is invalid")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "Owner name with numbers is invalid")]
        public async System.Threading.Tasks.Task OwnerNameWithNumbersIsInvalid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Owner name with numbers is invalid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 49
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
    await testRunner.GivenAsync("I have the owner \"Jane 123\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 51
    await testRunner.GivenAsync("I have a credit card number \"340000000000009\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 52
    await testRunner.GivenAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
    await testRunner.GivenAsync("I have the date \"09/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
    await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 56
    await testRunner.AndAsync("the response should contain validation error \"Wrong owner\" for field \"Owner\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Owner name with special characters is invalid")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "Owner name with special characters is invalid")]
        public async System.Threading.Tasks.Task OwnerNameWithSpecialCharactersIsInvalid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Owner name with special characters is invalid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
    await testRunner.GivenAsync("I have the owner \"Jane¤#&\"( J(/&\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
    await testRunner.GivenAsync("I have a credit card number \"340000000000009\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 61
    await testRunner.GivenAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
    await testRunner.GivenAsync("I have the date \"09/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 63
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
    await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 65
    await testRunner.AndAsync("the response should contain validation error \"Wrong owner\" for field \"Owner\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Owner name with alphanumeric characters is invalid")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "Owner name with alphanumeric characters is invalid")]
        public async System.Threading.Tasks.Task OwnerNameWithAlphanumericCharactersIsInvalid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Owner name with alphanumeric characters is invalid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 67
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 68
    await testRunner.GivenAsync("I have the owner \"Jan3 D03\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
    await testRunner.GivenAsync("I have a credit card number \"340000000000009\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 70
    await testRunner.GivenAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 71
    await testRunner.GivenAsync("I have the date \"09/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 74
    await testRunner.AndAsync("the response should contain validation error \"Wrong owner\" for field \"Owner\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Credit card number should be required")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "Credit card number should be required")]
        public async System.Threading.Tasks.Task CreditCardNumberShouldBeRequired()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Credit card number should be required", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 76
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 77
    await testRunner.GivenAsync("I have the owner \"Jane Doe\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 78
    await testRunner.GivenAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 79
    await testRunner.GivenAsync("I have the date \"09/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 80
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
    await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
    await testRunner.AndAsync("the response should contain validation error \"Number is required\" for field \"Numb" +
                        "er\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Credit card number with letters is invalid")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "Credit card number with letters is invalid")]
        public async System.Threading.Tasks.Task CreditCardNumberWithLettersIsInvalid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Credit card number with letters is invalid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 85
    await testRunner.GivenAsync("I have the owner \"Jane Doe\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 86
    await testRunner.GivenAsync("I have a credit card number \"340000000000abc\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 87
    await testRunner.GivenAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 88
    await testRunner.GivenAsync("I have the date \"09/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 89
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 90
    await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 91
    await testRunner.AndAsync("the response should contain validation error \"Wrong number\" for field \"Number\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Credit card number with special characters is invalid")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "Credit card number with special characters is invalid")]
        public async System.Threading.Tasks.Task CreditCardNumberWithSpecialCharactersIsInvalid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Credit card number with special characters is invalid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 93
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 94
    await testRunner.GivenAsync("I have the owner \"Jane Doe\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 95
    await testRunner.GivenAsync("I have a credit card number \"&4000000000000!\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 96
    await testRunner.GivenAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 97
    await testRunner.GivenAsync("I have the date \"09/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 98
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
    await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 100
    await testRunner.AndAsync("the response should contain validation error \"Wrong number\" for field \"Number\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CVV should be required")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "CVV should be required")]
        public async System.Threading.Tasks.Task CVVShouldBeRequired()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("CVV should be required", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 102
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 103
  await testRunner.GivenAsync("I have the owner \"John Doe\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 104
  await testRunner.AndAsync("I have a credit card number \"4111111111111111\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 105
  await testRunner.AndAsync("I have the date \"09/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
  await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 107
  await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 108
  await testRunner.AndAsync("the response should contain validation error \"Cvv is required\" for field \"Cvv\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CVV with letters is invalid")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "CVV with letters is invalid")]
        public async System.Threading.Tasks.Task CVVWithLettersIsInvalid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("CVV with letters is invalid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 110
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 111
    await testRunner.GivenAsync("I have the owner \"Jane Doe\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 112
    await testRunner.GivenAsync("I have a credit card number \"340000000000009\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 113
    await testRunner.GivenAsync("I have the CVV \"abc\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 114
    await testRunner.GivenAsync("I have the date \"09/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 115
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 116
    await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 117
    await testRunner.AndAsync("the response should contain validation error \"Wrong cvv\" for field \"Cvv\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CVV with special characters is invalid")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "CVV with special characters is invalid")]
        public async System.Threading.Tasks.Task CVVWithSpecialCharactersIsInvalid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("CVV with special characters is invalid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 119
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 120
    await testRunner.GivenAsync("I have the owner \"Jane Doe\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 121
    await testRunner.GivenAsync("I have a credit card number \"340000000000009\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 122
    await testRunner.GivenAsync("I have the CVV \"abc!\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 123
    await testRunner.GivenAsync("I have the date \"09/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 124
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 125
    await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 126
    await testRunner.AndAsync("the response should contain validation error \"Wrong cvv\" for field \"Cvv\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Date should be required")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "Date should be required")]
        public async System.Threading.Tasks.Task DateShouldBeRequired()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Date should be required", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 128
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 129
  await testRunner.GivenAsync("I have the owner \"John Doe\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 130
  await testRunner.AndAsync("I have a credit card number \"4111111111111111\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 131
  await testRunner.AndAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 132
  await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 133
  await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 134
  await testRunner.AndAsync("the response should contain validation error \"Date is required\" for field \"Date\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Date with letters is invalid")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "Date with letters is invalid")]
        public async System.Threading.Tasks.Task DateWithLettersIsInvalid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Date with letters is invalid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 136
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 137
    await testRunner.GivenAsync("I have the owner \"Jane Doe\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 138
    await testRunner.GivenAsync("I have a credit card number \"340000000000009\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 139
    await testRunner.GivenAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 140
    await testRunner.GivenAsync("I have the date \"ab/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 141
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 142
    await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 143
    await testRunner.AndAsync("the response should contain validation error \"Wrong date\" for field \"Date\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Date with special characters is invalid")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "Date with special characters is invalid")]
        public async System.Threading.Tasks.Task DateWithSpecialCharactersIsInvalid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Date with special characters is invalid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 145
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 146
    await testRunner.GivenAsync("I have the owner \"Jane Doe\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 147
    await testRunner.GivenAsync("I have a credit card number \"340000000000009\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 148
    await testRunner.GivenAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 149
    await testRunner.GivenAsync("I have the date \"0!/29\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 150
    await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 151
    await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 152
    await testRunner.AndAsync("the response should contain validation error \"Wrong date\" for field \"Date\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Date should not be expired")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Credit Card")]
        [Xunit.TraitAttribute("Description", "Date should not be expired")]
        public async System.Threading.Tasks.Task DateShouldNotBeExpired()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Date should not be expired", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 154
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 155
  await testRunner.GivenAsync("I have the owner \"John Doe\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 156
  await testRunner.AndAsync("I have a credit card number \"4111111111111111\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 157
  await testRunner.AndAsync("I have the date \"09/24\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
  await testRunner.AndAsync("I have the CVV \"123\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 159
  await testRunner.WhenAsync("I send a POST request to \"/CardValidation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 160
  await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 161
  await testRunner.AndAsync("the response should contain validation error \"Wrong date\" for field \"Date\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ValidateCreditCardFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ValidateCreditCardFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
